//
//  MainViewController+RemoteControl.m
//
//  Created by Brad Kammin on 12/3/14.
//
//

#import "MainViewController+RemoteControl.h"

@implementation MainViewController (RemoteControl)

// MainViewController is dynamically generated by 'cordova create', so
// add UIResponder methods to the MainViewController class to capture
// remote control events

// be cautious of other categories, or the main implementation, adding these methods (eg, it's possible Cordova might add them in a future version)

- (BOOL)canBecomeFirstResponder {
    return YES;
}

@end
